/**
 * Clean-Room High-Fidelity Anatomical SVG Tooth Geometry for DenToRa
 *
 * Coordinate space: 64 x 100 viewBox.
 *   Maxillary frame: cervical (gum) line at y ≈ 46, crowns extend DOWN to the
 *   occlusal plane (y ≈ 93), roots extend UP to y ≈ 4.
 *   Mandibular frame: generated by vertical mirroring (y → 100 − y) so crowns
 *   face UP toward the occlusal plane and roots extend DOWN to y ≈ 96.
 *
 * Every tooth class is authored as a layered 2.5D illustration:
 *   1. volumetric root trunks (separate shapes with open inter-radicular space)
 *   2. furcation depth shadows
 *   3. enamel crown body with warm ivory gradient
 *   4. clipped interior shading (cervical, distal, incisal translucency)
 *   5. occlusal table plate with raised cusp highlights + recessed grooves
 *   6. glossy specular labial sheen
 *   7. faint translucent pulp chamber & root canals
 *
 * All path data is authored from first human dental anatomical principles.
 * Left-sided teeth (Q2/Q3) are derived by horizontal mirroring of the right
 * master forms so distal root curvature and incisal asymmetry face the arch.
 */

import {
  ToothAnatomyGroup,
  ToothPosition,
  ToothSide,
  ToothSpecificType,
} from '../types/odontogram'

// ─── PUBLIC GEOMETRY CONTRACT ────────────────────────────────────────────────

export interface ToothGeometryPaths {
  rootOutline: string
  rootDetails?: string[]
  crownOutline: string
  crownDetails?: string[]
  pulpOutline: string
  rootCanalPaths: string[]
  surfaces: {
    mesial: string
    distal: string
    occlusal: string
    buccal: string
    lingual: string
  }
  implantOutline: string
  implantThreads: string[]
  crownCapOutline: string
  apexCenter: { x: number; y: number }
  apices?: Array<{ x: number; y: number }>
  gumLinePath: string
  fractureCrackPath: string
  fissurePaths?: string[]
  cuspHighlights?: string[]
  rootSeparationPath?: string
  cervicalLinePath?: string
  rootCount: number
  canalCount: number
  relativeWidth?: number

  // ── Volumetric 2.5D layering (new) ──
  /** Separate root trunk silhouettes (1 = single, 2 = bifurcated, 3 = trifurcated). */
  rootTrunks: string[]
  /** Soft dark blobs at root apices. */
  rootApexShadows: VolBlob[]
  /** Engraved developmental grooves running down root trunks. */
  rootGrooves: string[]
  /** Dark soft shapes in the inter-radicular furcation notches. */
  furcationShadows: string[]
  /** Merged cervical base block extending root trunks behind the crown. */
  cervicalSkirt?: string
  /** Blurred interior crown shadows (cervical band, side falloff, incisal translucency). */
  crownShades: VolBlob[]
  /** Soft cusp-base / fossa shadows rendered ON the occlusal table. */
  occlusalShades: VolBlob[]
  /** Interior light: cusp highlights, labial gloss, incisal translucency. */
  crownLights: VolBlob[]
  /** Recessed occlusal table plate (molars/premolars). */
  occlusalTablePath?: string
  /** Soft shadow band where the table plate meets the labial face. */
  tableTopShade?: VolBlob
  /** Engraved grooves on the occlusal table. */
  occlusalGrooves: string[]
  /** Light ridge lines on the occlusal table (oblique ridge etc.). */
  occlusalRidges?: string[]
}

/** A soft elliptical shading/light blob. */
export interface VolBlob {
  cx: number
  cy: number
  rx: number
  ry: number
  fill: string
  opacity: number
  /** 'soft' = σ1 blur, 'wide' = σ2 blur, undefined = crisp. */
  blur?: 'soft' | 'wide'
  /** Render with the shared radial cusp-light gradient (used for cusp volumes). */
  radial?: boolean
  /** Clockwise rotation in degrees around (cx, cy) — oriented cusp ridges. */
  rot?: number
}

export interface BBox {
  x0: number
  x1: number
  y0: number
  y1: number
}

// ─── PATH TRANSFORM UTILITIES ────────────────────────────────────────────────
// Every authored path uses `M x,y C x,y x,y x,y ... Q x,y x,y Z` token pairs,
// which makes coordinate transforms safe and deterministic.

const r1 = (n: number) => Math.round(n * 10) / 10

function transformPathD(d: string, fx: number, fy: number, ox = 32, oy = 50): string {
  const tokens = d.trim().split(/\s+/)
  const out: string[] = []
  for (const t of tokens) {
    if (t.length > 0 && /[A-Za-z]/.test(t.charAt(0))) {
      out.push(t)
    } else {
      const [xs, ys] = t.split(',').map(Number)
      out.push(`${r1(ox + (xs - ox) * fx)},${r1(oy + (ys - oy) * fy)}`)
    }
  }
  return out.join(' ')
}

function transformBlob(b: VolBlob, fx: number, fy: number, ox = 32, oy = 50): VolBlob {
  return {
    ...b,
    cx: r1(ox + (b.cx - ox) * fx),
    cy: r1(oy + (b.cy - oy) * fy),
    rx: Math.max(0.3, r1(b.rx * Math.abs(fx))),
    ry: Math.max(0.3, r1(b.ry * Math.abs(fy))),
    // A single-axis mirror flips handedness: the ridge angle must negate.
    ...(b.rot !== undefined && fx * fy < 0 ? { rot: -b.rot } : {}),
  }
}

function transformPts(pts: Array<{ x: number; y: number }>, fx: number, fy: number, ox = 32, oy = 50) {
  return pts.map((p) => ({ x: r1(ox + (p.x - ox) * fx), y: r1(oy + (p.y - oy) * fy) }))
}

/** Horizontal mirror (left-sided teeth). */
function flipX(d: string) {
  return transformPathD(d, -1, 1)
}
function flipXBlob(b: VolBlob) {
  return transformBlob(b, -1, 1)
}
/** Vertical mirror (mandibular frame). */
function mirrorY(d: string) {
  return transformPathD(d, 1, -1)
}
function mirrorYBlob(b: VolBlob) {
  return transformBlob(b, 1, -1)
}

function pathBBox(d: string): BBox {
  let x0 = Infinity
  let x1 = -Infinity
  let y0 = Infinity
  let y1 = -Infinity
  for (const t of d.trim().split(/\s+/)) {
    if (/[A-Za-z]/.test(t.charAt(0))) continue
    const [xs, ys] = t.split(',').map(Number)
    x0 = Math.min(x0, xs)
    x1 = Math.max(x1, xs)
    y0 = Math.min(y0, ys)
    y1 = Math.max(y1, ys)
  }
  return { x0, x1, y0, y1 }
}

function rectPath(x0: number, y0: number, x1: number, y1: number): string {
  return `M ${r1(x0)},${r1(y0)} L ${r1(x1)},${r1(y0)} L ${r1(x1)},${r1(y1)} L ${r1(x0)},${r1(y1)} Z`
}

/**
 * Five-surface interactive partition of the crown bounding box.
 * Zones are plain rectangles; the SVG clips them to the organic crown
 * silhouette so hover fills always follow the enamel contour.
 */
function buildSurfaces(bb: BBox, isRightSide: boolean, isUpper: boolean): ToothGeometryPaths['surfaces'] {
  const x0 = bb.x0 + 0.4
  const x1 = bb.x1 - 0.4
  const y0 = bb.y0 + 0.6
  const y1 = bb.y1 - 0.4
  const w = x1 - x0
  const h = y1 - y0
  const side = w * 0.22

  const [mX0, mX1] = isRightSide ? [x0, x0 + side] : [x1 - side, x1]
  const [dX0, dX1] = isRightSide ? [x1 - side, x1] : [x0, x0 + side]
  const cX0 = Math.min(mX1, dX0)
  const cX1 = Math.max(mX0, dX1)

  // Maxillary: buccal (labial) band near cervical, lingual band mid, occlusal band at edge.
  // Mandibular: buccal band near incisal edge, occlusal mid, lingual near cervical.
  const b1 = isUpper ? y0 + h * 0.36 : y0 + h * 0.3
  const b2 = isUpper ? y0 + h * 0.68 : y0 + h * 0.66

  const midRect = rectPath(cX0, b1, cX1, b2)
  const edgeRect = rectPath(cX0, b2, cX1, y1)

  return {
    mesial: rectPath(mX0, y0, mX1, y1),
    distal: rectPath(dX0, y0, dX1, y1),
    buccal: rectPath(cX0, y0, cX1, b1),
    lingual: isUpper ? midRect : edgeRect,
    occlusal: isUpper ? edgeRect : midRect,
  }
}

// ─── INTERNAL CLASS CONFIG (right-sided maxillary master frame) ──────────────

interface CrownBase {
  outline: string
  details: string[]
  shades: VolBlob[]
  lights: VolBlob[]
  pulp: string
  gum: string
  cervical: string
  relWidth: number
  apexCenter: { x: number; y: number }
}

interface OcclusalSet {
  table?: string
  tableTopShade?: VolBlob
  shades: VolBlob[]
  lights: VolBlob[]
  grooves: string[]
  ridges?: string[]
}

interface RootSet {
  trunks: string[]
  furcations: string[]
  apexShadows: VolBlob[]
  grooves: string[]
  canals: string[]
  apices: Array<{ x: number; y: number }>
  rootCount: number
  canalCount: number
}

interface ToothClass {
  crown: CrownBase
  occlusal: OcclusalSet
  roots: RootSet
  fracture: string
}

// Shared warm shading palette
const SHADE_DISTAL = '#8A744E'
const SHADE_MESIAL = '#8A744E'
const SHADE_CERVICAL = '#C9A85C'
const SHADE_INCISAL = '#6B7E94'
const SHADE_CUSP = '#7A6030'
const LIGHT = '#FFFFFF'

const cuspLight = (cx: number, cy: number, r: number, o = 0.8): VolBlob => ({
  cx,
  cy,
  rx: r,
  ry: r,
  fill: LIGHT,
  opacity: o,
  radial: true,
})
/** Elongated, optionally tilted cusp-ridge highlight — reads as a sculpted mound. */
const cuspRidge = (cx: number, cy: number, rx: number, ry: number, rot = 0, o = 0.9): VolBlob => ({
  cx,
  cy,
  rx,
  ry,
  rot,
  fill: LIGHT,
  opacity: o,
  radial: true,
})
const cuspShade = (cx: number, cy: number, rx: number, ry: number, o = 0.3): VolBlob => ({
  cx,
  cy,
  rx,
  ry,
  fill: SHADE_CUSP,
  opacity: o,
  blur: 'wide',
})
const gloss = (cx: number, cy: number, rx: number, ry: number, o = 0.4): VolBlob => ({
  cx,
  cy,
  rx,
  ry,
  fill: LIGHT,
  opacity: Math.min(0.62, o * 1.15),
  blur: 'wide',
})
const edgeShade = (cx: number, cy: number, rx: number, ry: number, o = 0.25, fill = SHADE_DISTAL): VolBlob => ({
  cx,
  cy,
  rx,
  ry,
  fill,
  opacity: Math.min(0.5, o * 1.45),
  blur: 'wide',
})
const cervical = (cx: number, cy: number, rx: number, ry: number, o = 0.2): VolBlob => ({
  cx,
  cy,
  rx,
  ry,
  fill: SHADE_CERVICAL,
  opacity: Math.min(0.45, o * 1.3),
  blur: 'wide',
})
const apexShadow = (x: number, y: number, rx: number, ry: number): VolBlob => ({
  cx: x,
  cy: y,
  rx,
  ry,
  fill: '#5C420F',
  opacity: 0.45,
  blur: 'soft',
})

// ══════════════════════════════════════════════════════════════════════════════
// MAXILLARY MASTER CLASSES (right-sided frame, Q1)
// ══════════════════════════════════════════════════════════════════════════════

const UP11: ToothClass = {
  crown: {
    // Broad labial face, nearly parallel sides, flat chisel incisal edge
    outline:
      'M 18.5,47 C 16.8,56 16.4,68 17.1,78 C 17.5,83.5 18.3,88 20.8,90.2 C 25.5,92.4 35,92.4 39.5,90.2 C 42,88 42.9,83.5 43.2,78 C 43.9,68 43.5,56 41.8,47 C 35,50.4 25.5,50.4 18.5,47 Z',
    details: [
      'M 24.8,53 C 24.2,64 24,75 24.6,87',
      'M 38.6,53 C 39.2,64 39.4,75 38.9,87',
    ],
    shades: [
      cervical(31, 52, 13.5, 4),
      edgeShade(42.6, 68, 2.8, 15, 0.22),
      edgeShade(17.6, 68, 2.4, 15, 0.12, SHADE_MESIAL),
      { cx: 31, cy: 90.4, rx: 11.5, ry: 3, fill: SHADE_INCISAL, opacity: 0.27, blur: 'wide' },
    ],
    lights: [
      gloss(26.5, 66, 6.2, 14, 0.42),
      { cx: 25.6, cy: 59.5, rx: 2.2, ry: 6.5, fill: LIGHT, opacity: 0.5, blur: 'soft' },
      { cx: 31, cy: 90.8, rx: 10.5, ry: 1.7, fill: LIGHT, opacity: 0.4, blur: 'soft' },
    ],
    pulp:
      'M 27.5,53 C 26,58.5 26,67.5 27.4,73 C 29.2,76 34.8,76 36.6,73 C 38,67.5 38,58.5 36.5,53 C 33.5,55.6 30,55.6 27.5,53 Z',
    gum: 'M 13.5,47 Q 31,52.5 47.5,47',
    cervical: 'M 18.5,47 Q 31,51 41.8,47',
    relWidth: 1.15,
    apexCenter: { x: 32, y: 8 },
  },
  occlusal: { shades: [], lights: [], grooves: [] },
  roots: {
    trunks: [
      // Flat ribbon-like root, clearly narrower than the crown
      'M 23.5,48 C 22.3,38 23,23 28.8,9.5 C 29.8,7 33.4,7 34.3,9.5 C 39.5,21.5 40.3,37 40.8,48 C 35,51.2 28.5,51.2 23.5,48 Z',
    ],
    furcations: [],
    apexShadows: [apexShadow(32.2, 12, 2.6, 3.4)],
    grooves: ['M 32,13 C 31.5,24 31.5,35 32,44'],
    canals: ['M 32,11 C 31.4,23 31.4,36 32,50'],
    apices: [{ x: 32, y: 8 }],
    rootCount: 1,
    canalCount: 1,
  },
  fracture: 'M 22,49 L 30,64 L 26,76 L 36,92',
}

const UP12: ToothClass = {
  crown: {
    // Narrower, more delicate; distal incisal corner softly rounded
    outline:
      'M 20.5,47 C 19,56 18.6,68 19.2,77.5 C 19.5,82.5 20.2,86.5 22.4,88.8 C 26.5,91.2 33.5,91.2 37.4,88.6 C 39.7,86.3 40.6,81.8 40.9,76.5 C 41.3,67 40.8,56 39.3,47 C 33,50.3 25.5,50.3 20.5,47 Z',
    details: [
      'M 26.2,53 C 25.7,64 25.5,75 26.1,86',
      'M 37.4,53 C 38,63 38.1,74 37.7,84',
    ],
    shades: [
      cervical(30.3, 52, 11, 3.8),
      edgeShade(40.2, 67, 2.6, 14, 0.24),
      edgeShade(19.7, 66, 2.1, 14, 0.12, SHADE_MESIAL),
      { cx: 30.3, cy: 89, rx: 9.5, ry: 2.8, fill: SHADE_INCISAL, opacity: 0.27, blur: 'wide' },
    ],
    lights: [
      gloss(25.8, 63.5, 5.2, 12.5, 0.4),
      { cx: 25.2, cy: 58, rx: 1.9, ry: 6, fill: LIGHT, opacity: 0.48, blur: 'soft' },
      { cx: 30.3, cy: 89.6, rx: 8, ry: 1.6, fill: LIGHT, opacity: 0.38, blur: 'soft' },
    ],
    pulp:
      'M 26.8,53 C 25.4,58.5 25.4,67 26.7,72 C 28.3,75 33.3,75 34.9,72 C 36.2,67 36.2,58.5 34.9,53 C 32.1,55.4 29.2,55.4 26.8,53 Z',
    gum: 'M 16,47 Q 31,52 45.5,47',
    cervical: 'M 20.5,47 Q 31,50.8 39.3,47',
    relWidth: 0.9,
    apexCenter: { x: 33.5, y: 9.5 },
  },
  occlusal: { shades: [], lights: [], grooves: [] },
  roots: {
    trunks: [
      'M 25.8,48 C 24.9,38 26.3,23 31.8,11.5 C 32.8,9.2 35.6,9.6 36.2,11.8 C 39.7,22.5 40.5,37 39.8,48 C 35,50.9 30.2,50.9 25.8,48 Z',
    ],
    furcations: [],
    apexShadows: [apexShadow(33.8, 14, 2.4, 3.2)],
    grooves: ['M 32.9,15.5 C 32.4,26 32.8,36 33,44'],
    canals: ['M 33.8,13 C 32.2,24 32,36 32.2,50'],
    apices: [{ x: 33.5, y: 9.5 }],
    rootCount: 1,
    canalCount: 1,
  },
  fracture: 'M 23.5,49 L 30,63 L 27.5,74 L 35.5,90',
}

const UP13: ToothClass = {
  crown: {
    // Spear-shaped: convex labial face converging to a distinct pointed cusp
    outline:
      'M 19.5,47 C 16.4,56 15.4,69 17.4,79.5 C 18.6,86 22.5,91.5 26.5,94.6 C 28.6,96.2 30.4,97 32,97.1 C 33.6,97 35.4,96.2 37.5,94.6 C 41.5,91.5 45.4,86 46.6,79.5 C 48,69 46.8,56 43.4,47 C 36,50.6 26,50.6 19.5,47 Z',
    details: [
      'M 24.5,56 C 25.5,68 27.5,82 30.2,92.5',
      'M 39.5,56 C 38.5,68 36.5,82 33.8,92.5',
      'M 32,51.5 C 31.6,64 31.6,78 32,92',
    ],
    shades: [
      cervical(31.5, 52, 12.5, 3.8),
      edgeShade(45.8, 68, 3.4, 15, 0.24),
      edgeShade(17.8, 68, 2.5, 15, 0.13, SHADE_MESIAL),
      cuspShade(24.8, 76, 4.2, 10.5, 0.2),
      cuspShade(39.2, 76, 4.2, 10.5, 0.2),
      { cx: 32, cy: 94, rx: 7.5, ry: 2.6, fill: SHADE_INCISAL, opacity: 0.25, blur: 'wide' },
    ],
    lights: [
      cuspLight(32, 88.5, 6.5, 0.9),
      gloss(26.5, 59, 5, 11.5, 0.4),
      { cx: 26, cy: 54.5, rx: 1.9, ry: 6, fill: LIGHT, opacity: 0.48, blur: 'soft' },
    ],
    pulp:
      'M 26.5,53 C 25,60 25,71 27,78.5 C 29,83 35,83 37,78.5 C 39,71 39,60 37.5,53 C 34,55.8 30,55.8 26.5,53 Z',
    gum: 'M 14,47 Q 31,52.5 47.5,47',
    cervical: 'M 19.5,47 Q 31,51 43.4,47',
    relWidth: 1.05,
    apexCenter: { x: 33, y: 4 },
  },
  occlusal: { shades: [], lights: [], grooves: [] },
  roots: {
    trunks: [
      'M 21,48 C 19.6,34 21,14 30,4.5 C 31.4,2.8 34.6,2.8 36,4.5 C 44,14 44.6,34 43,48 C 35.5,51.8 27.5,51.8 21,48 Z',
    ],
    furcations: [],
    apexShadows: [apexShadow(33.5, 8, 3.4, 4.2)],
    grooves: [
      'M 29.5,10 C 29,24 29,36 29.8,45',
      'M 34.5,10 C 35,24 35,36 34.2,45',
    ],
    canals: ['M 32,8 C 31.4,22 31.4,36 32,50'],
    apices: [{ x: 33, y: 4 }],
    rootCount: 1,
    canalCount: 1,
  },
  fracture: 'M 22,49 L 29,63 L 26,76 L 32,94',
}

const UP14: ToothClass = {
  crown: {
    outline:
      'M 18,47 C 15.2,55 14.4,67 15.6,77 C 16.4,83 18.5,88 22.5,90.6 C 26,92.8 29.8,92.9 32.6,91.4 C 33.8,90.7 35,90.7 36.2,91.4 C 40.5,93.4 44.5,90.5 45.8,84.5 C 47.2,77 46.8,56 44,47 C 36,50.5 25.5,50.5 18,47 Z',
    details: [
      'M 22,55 C 21.5,64 21.5,74 22.5,84',
      'M 41,55 C 41.6,64 41.6,74 40.6,83',
    ],
    shades: [
      cervical(31, 52, 12.5, 3.7),
      edgeShade(45, 66, 3.4, 14, 0.27),
      edgeShade(16.8, 64, 2.6, 13.5, 0.15, SHADE_MESIAL),
    ],
    lights: [gloss(24, 58, 5, 10, 0.38), { cx: 23.5, cy: 54, rx: 1.9, ry: 5.5, fill: LIGHT, opacity: 0.45, blur: 'soft' }],
    pulp:
      'M 23,53 C 21.5,60 21.5,70 23.5,76 C 25.5,79 38.5,79 40.5,76 C 42.5,70 42.5,60 41,53 C 37,55.8 27,55.8 23,53 Z',
    gum: 'M 13,47 Q 31,52 48.5,47',
    cervical: 'M 18,47 Q 31,50.8 44,47',
    relWidth: 1.05,
    apexCenter: { x: 32.5, y: 7 },
  },
  occlusal: {
    table:
      'M 19.5,64 C 25,61.2 38,61.2 43.5,64 C 45.5,70 45.3,78.5 43.6,84.5 C 39,89.3 25.5,89.3 21,84.5 C 19.2,78.5 19,70 19.5,64 Z',
    tableTopShade: { cx: 31.5, cy: 63.5, rx: 12.5, ry: 3.2, fill: SHADE_CUSP, opacity: 0.36, blur: 'wide' },
    shades: [cuspShade(26, 70, 5.5, 5, 0.26), cuspShade(39, 69.5, 5, 4.8, 0.26), cuspShade(32.5, 84.5, 3.6, 2.4, 0.14)],
    lights: [cuspRidge(26, 84.5, 6.8, 4.6, -10, 0.95), cuspRidge(39, 83.5, 6.2, 4.3, 10, 0.9)],
    grooves: ['M 32.5,64 C 32.2,71 32.2,78 32.5,86.5'],
  },
  roots: {
    trunks: [
      'M 18.5,48 C 17,37 17.5,19 22.5,8.5 C 23.6,6.2 26.8,6.4 27.6,8.8 C 30.6,19 31,36 30,48 C 26,50.6 22,50.6 18.5,48 Z',
      'M 34.5,48 C 34,37 35,19 38.8,10 C 39.8,7.6 42.8,8 43.4,10.5 C 45.8,20 46,36 45.2,48 C 41.5,50.6 37.5,50.6 34.5,48 Z',
    ],
    furcations: [
      'M 30,48 C 30.2,41 30.6,35 31.5,30 C 32.4,35 32.8,41 33,48 C 32,49.4 31,49.4 30,48 Z',
    ],
    apexShadows: [apexShadow(24.8, 11.5, 3, 3.8), apexShadow(40.5, 13, 3, 3.8)],
    grooves: [
      'M 24,14 C 23.6,24 24,34 24.6,44',
      'M 40.5,15 C 41,24 40.6,34 40.2,44',
    ],
    canals: [
      'M 24.5,10 C 24,22 24.5,36 26,52',
      'M 40,11 C 40.5,22 40,36 38,52',
    ],
    apices: [
      { x: 24.8, y: 7.5 },
      { x: 40.8, y: 8.8 },
    ],
    rootCount: 2,
    canalCount: 2,
  },
  fracture: 'M 21,49 L 29,64 L 25,76 L 35,92',
}

const UP15: ToothClass = {
  crown: {
    outline:
      'M 17.5,47 C 14.8,55 14,68 15.2,78 C 16,84.5 18.2,89.5 22.8,91.8 C 27.5,94 36.5,94 41.2,91.4 C 45,89 47,82.5 47.4,76 C 48,65 46.8,55 44,47 C 36,50.5 25,50.5 17.5,47 Z',
    details: [
      'M 21.5,55 C 21,64 21,74 22,84',
      'M 41.5,55 C 42.1,64 42.1,74 41.2,83.5',
    ],
    shades: [
      cervical(31.5, 52, 12.8, 3.7),
      edgeShade(46, 68, 3.4, 15, 0.27),
      edgeShade(16, 66, 2.6, 14, 0.15, SHADE_MESIAL),
    ],
    lights: [gloss(24, 58, 5.5, 11, 0.4), { cx: 23.5, cy: 54, rx: 2, ry: 6, fill: LIGHT, opacity: 0.45, blur: 'soft' }],
    pulp:
      'M 22.5,53 C 21,60 21,70 23,76 C 25,79 38,79 40,76 C 42,70 42,60 40.5,53 C 36.5,55.8 26.5,55.8 22.5,53 Z',
    gum: 'M 12.5,47 Q 31,52 49,47',
    cervical: 'M 17.5,47 Q 31,50.8 44,47',
    relWidth: 1.0,
    apexCenter: { x: 32, y: 5 },
  },
  occlusal: {
    table:
      'M 19,64 C 24.8,61.2 38.8,61.2 44.5,64 C 46.5,70.5 46.2,79 44.3,85 C 38.8,90.3 24.8,90.3 20.4,85 C 18.5,79 18.2,70.5 19,64 Z',
    tableTopShade: { cx: 31.8, cy: 63.5, rx: 13, ry: 3.2, fill: SHADE_CUSP, opacity: 0.36, blur: 'wide' },
    shades: [cuspShade(26.5, 70, 5.5, 5, 0.26), cuspShade(39, 70, 5.5, 5, 0.26), cuspShade(32.8, 84.5, 3.8, 2.4, 0.14)],
    lights: [cuspRidge(26.5, 84.5, 6.6, 4.5, -10, 0.95), cuspRidge(39, 84, 6.4, 4.4, 10, 0.92)],
    grooves: ['M 32.5,64 C 32.2,72 32.2,79 32.5,87.5'],
  },
  roots: {
    trunks: [
      'M 20,48 C 18.4,36 19.5,16 28,6 C 29.5,3.6 34.5,3.6 36,6 C 43.5,16 44.5,36 43,48 C 35.5,51.8 27,51.8 20,48 Z',
    ],
    furcations: [],
    apexShadows: [apexShadow(32.5, 9, 3.4, 4.2)],
    grooves: [
      'M 29,11 C 28.4,24 28.6,36 29.4,45',
      'M 34,11 C 34.6,24 34.4,36 33.8,45',
    ],
    canals: [
      'M 28.5,8 C 27.8,22 28,36 29.5,52',
      'M 35,8 C 35.8,22 35.4,36 34,52',
    ],
    apices: [{ x: 32, y: 5 }],
    rootCount: 1,
    canalCount: 2,
  },
  fracture: 'M 21,49 L 29,64 L 25,77 L 36,93',
}

const UP16: ToothClass = {
  crown: {
    outline:
      'M 10,47 C 7.2,55 6,68 7.2,79 C 7.9,85 9.8,90.5 14.2,93 C 18,95 22.4,94.9 25.6,93.4 C 27,92.7 28.4,92.7 29.8,93.4 C 33.6,95.1 39,95.3 43.2,93.6 C 47.2,91.8 50.2,87.5 51.2,81.5 C 52.4,72 52.2,56 49.5,47 C 40,50.6 19,50.6 10,47 Z',
    details: [
      'M 15,55 C 14.2,65 14.2,76 15.4,86',
      'M 46,55 C 46.8,65 46.8,76 45.6,85.5',
    ],
    shades: [
      cervical(30.5, 52, 16.5, 3.9),
      edgeShade(50.5, 66, 3.8, 16, 0.28),
      edgeShade(8, 66, 3, 16, 0.18, SHADE_MESIAL),
    ],
    lights: [gloss(22, 58, 6, 11, 0.36), { cx: 21.5, cy: 54, rx: 2.1, ry: 6, fill: LIGHT, opacity: 0.42, blur: 'soft' }],
    pulp:
      'M 19,54 C 17,60 17,72 19.5,78 C 23,82 40,82 43.5,78 C 46,72 46,60 44,54 C 38,57.5 25,57.5 19,54 Z',
    gum: 'M 5,47 Q 30.5,53 55.5,47',
    cervical: 'M 10,47 Q 30,51 49.5,47',
    relWidth: 1.35,
    apexCenter: { x: 31.5, y: 5 },
  },
  occlusal: {
    table:
      'M 12.5,63.5 C 19.5,60.5 43.5,60.5 50.5,63.5 C 52.8,70 52.5,78 50.8,84 C 45,90 19,90 13.2,84 C 11.4,78 11.2,70 12.5,63.5 Z',
    tableTopShade: { cx: 31.5, cy: 63, rx: 18.5, ry: 3.6, fill: SHADE_CUSP, opacity: 0.3, blur: 'wide' },
    shades: [
      cuspShade(31, 74, 9, 7.5, 0.34),
      cuspShade(19, 68.5, 5, 4.5, 0.2),
      cuspShade(42, 68.5, 5, 4.5, 0.2),
      cuspShade(19, 75.2, 3.4, 3.6, 0.13),
      cuspShade(42.5, 75.2, 3.4, 3.6, 0.13),
    ],
    lights: [
      cuspRidge(19, 70, 7.2, 4.8, -14, 0.95),
      cuspRidge(42, 70, 6.8, 4.6, 14, 0.95),
      cuspRidge(18.5, 81, 6, 4, -10, 0.9),
      cuspRidge(43, 81, 6, 4, 10, 0.9),
    ],
    grooves: [
      'M 31,63.5 C 30.7,70 30.7,78 31,85',
      'M 14.5,73.5 C 24,75.8 38,75.8 48.5,73.5',
    ],
    ridges: ['M 18.5,67 C 26,72.5 36.5,79.5 43.5,84.5'],
  },
  roots: {
    trunks: [
      'M 11,48 C 9,38 8.5,20 11.5,9 C 12.4,6.5 15.6,6.2 16.5,8.8 C 19,19.5 20.5,36 22,48 C 18,50.6 14,50.6 11,48 Z',
      'M 25.5,48 C 24.4,38 25,16 29.5,6 C 30.5,3.4 33.8,3.4 34.8,6 C 37.8,16 37.6,38 36.8,48 C 33,50.8 28.5,50.8 25.5,48 Z',
      'M 40.5,48 C 39.5,38 40.5,18.5 46,10.5 C 47.5,8.2 50.5,8.8 51,11.2 C 53.2,22.5 52.8,38 50.5,48 C 46.5,50.6 43.5,50.6 40.5,48 Z',
    ],
    furcations: [
      'M 21,48 C 21.5,39 22.5,32 24.5,26 C 26.5,32 27.2,39 27.6,48 C 25.5,49.8 23,49.8 21,48 Z',
      'M 36.2,48 C 36.6,39 37.4,32 39,26.5 C 40.6,32 41.3,39 41.6,48 C 39.5,49.8 37.8,49.8 36.2,48 Z',
    ],
    apexShadows: [
      apexShadow(14.5, 12, 3, 3.8),
      apexShadow(32, 9.5, 3, 3.8),
      apexShadow(48, 14, 3, 3.8),
    ],
    grooves: [
      'M 15,14 C 14.6,25 15.4,36 16.4,45',
      'M 31,10 C 30.6,22 30.8,36 31.2,45',
      'M 46,15 C 46.5,25 45.8,36 44.6,45',
    ],
    canals: [
      'M 14,10 C 14.5,24 18,38 21,54',
      'M 31,7 C 30.6,22 30.6,38 31,54',
      'M 48,11 C 47.5,24 44,38 41,54',
    ],
    apices: [
      { x: 14, y: 7.8 },
      { x: 32, y: 5 },
      { x: 48.5, y: 9.8 },
    ],
    rootCount: 3,
    canalCount: 4,
  },
  fracture: 'M 13,49 L 24,66 L 20,78 L 36,94',
}

const UP17: ToothClass = {
  crown: {
    outline:
      'M 11,47 C 8.5,55 7.4,68 8.5,78.5 C 9.2,84.5 11,89.8 15,92.2 C 18.6,94.1 22.6,94 25.6,92.6 C 27,91.9 28.4,91.9 29.8,92.6 C 33.4,94.2 38.4,94.3 42.2,92.8 C 46,91 48.8,87 49.7,81 C 50.8,72 50.6,56 48.5,47 C 39.5,50.5 19.5,50.5 11,47 Z',
    details: [
      'M 16,55 C 15.3,64.5 15.3,75 16.4,84.5',
      'M 44.5,55 C 45.2,64.5 45.2,75 44.2,84',
    ],
    shades: [
      cervical(30, 52, 15.5, 3.8),
      edgeShade(49, 66, 3.6, 15.5, 0.28),
      edgeShade(9, 66, 3, 15.5, 0.18, SHADE_MESIAL),
    ],
    lights: [gloss(22, 58, 5.5, 10.5, 0.35), { cx: 21.5, cy: 54, rx: 2, ry: 5.8, fill: LIGHT, opacity: 0.4, blur: 'soft' }],
    pulp:
      'M 20,54.5 C 18.2,60 18.2,71 20.5,76.5 C 24,80 38.5,80 42,76.5 C 44.3,71 44.3,60 42.5,54.5 C 37,57.6 25.5,57.6 20,54.5 Z',
    gum: 'M 6,47 Q 30,52.8 54.5,47',
    cervical: 'M 11,47 Q 30,50.8 48.5,47',
    relWidth: 1.25,
    apexCenter: { x: 31.8, y: 5.8 },
  },
  occlusal: {
    table:
      'M 13,63.5 C 20,60.8 43,60.8 49.5,63.5 C 51.5,70 51.2,77.5 49.4,83 C 44,89 19.8,89 14.6,83 C 12.7,77.5 12.5,70 13,63.5 Z',
    tableTopShade: { cx: 31.2, cy: 63, rx: 17.5, ry: 3.4, fill: SHADE_CUSP, opacity: 0.3, blur: 'wide' },
    shades: [
      cuspShade(31, 73.5, 8, 7, 0.34),
      cuspShade(19.5, 69, 4.8, 4.2, 0.2),
      cuspShade(41, 69, 4.8, 4.2, 0.2),
      cuspShade(19.2, 75, 3.2, 3.5, 0.13),
      cuspShade(41.5, 75, 3.2, 3.5, 0.13),
    ],
    lights: [
      cuspRidge(19.5, 70, 6.6, 4.5, -14, 0.95),
      cuspRidge(41, 70, 6.2, 4.3, 14, 0.92),
      cuspRidge(19, 80, 5.8, 3.8, -10, 0.9),
      cuspRidge(42, 80, 5.6, 3.8, 10, 0.88),
    ],
    grooves: [
      'M 30.8,63.5 C 30.6,70 30.6,77 30.8,84',
      'M 15.5,73 C 24.5,75.3 37.5,75.3 47,73',
    ],
    ridges: ['M 19,67 C 26.5,72.5 36.5,79 43,83.5'],
  },
  roots: {
    trunks: [
      'M 12.5,48 C 10.8,38 10.8,21 14,10 C 14.9,7.5 17.8,7.3 18.6,9.8 C 20.8,20 21.8,36 23,48 C 19.3,50.5 15.8,50.5 12.5,48 Z',
      'M 26,48 C 25,38 25.6,17 29.8,7 C 30.8,4.6 33.6,4.6 34.5,7 C 37.4,17 37.2,38 36.4,48 C 33,50.7 29,50.7 26,48 Z',
      'M 40,48 C 39.2,38 40,19 44.8,11.5 C 46.2,9.2 49,9.8 49.4,12.2 C 51.2,23 50.6,38 48.6,48 C 45.2,50.5 42.6,50.5 40,48 Z',
    ],
    furcations: [
      'M 22.4,48 C 22.8,40 23.7,33.5 25.2,28 C 26.6,33.5 27.2,40 27.5,48 C 25.5,49.8 23.8,49.8 22.4,48 Z',
      'M 36.2,48 C 36.6,40 37.3,33.5 38.6,28.5 C 40,33.5 40.6,40 40.9,48 C 39,49.8 37.6,49.8 36.2,48 Z',
    ],
    apexShadows: [
      apexShadow(16.5, 13, 3, 3.8),
      apexShadow(32, 10, 3, 3.8),
      apexShadow(46.5, 15, 3, 3.8),
    ],
    grooves: [
      'M 16.5,15 C 16.2,26 17,36 17.8,45',
      'M 31.5,11 C 31.2,22 31.3,36 31.5,45',
      'M 45.5,16 C 45.8,26 45.2,36 44.2,45',
    ],
    canals: [
      'M 15.5,11 C 16,24 19,37 21.8,54',
      'M 31,7.5 C 30.7,22 30.7,37 31,54',
      'M 46.5,12 C 46,24 43,37 40.5,54',
    ],
    apices: [
      { x: 16, y: 8.8 },
      { x: 32, y: 5.8 },
      { x: 47, y: 10.6 },
    ],
    rootCount: 3,
    canalCount: 3,
  },
  fracture: 'M 14,49 L 24,65 L 20,77 L 35,93',
}

const UP18: ToothClass = {
  crown: {
    outline:
      'M 12,47 C 9.5,54.5 8.6,67 9.8,77 C 10.5,83 12.4,88.5 16.5,91 C 20,93 24,93 27,91.8 C 28.4,91.2 29.8,91.2 31.2,91.8 C 35,93.3 40,93.4 43.5,91.5 C 46.8,89.5 49.2,85.5 50,80 C 51,71 50.6,55 48.5,47 C 39.5,50.5 20,50.5 12,47 Z',
    details: [
      'M 17,55 C 16.4,64 16.4,74 17.4,83.5',
      'M 44,55 C 44.6,64 44.6,74 43.8,83',
    ],
    shades: [
      cervical(30.5, 52, 15.5, 3.7),
      edgeShade(48.5, 66, 3.4, 15, 0.28),
      edgeShade(10, 66, 3, 15, 0.18, SHADE_MESIAL),
    ],
    lights: [gloss(22.5, 58, 5.5, 10.5, 0.35), { cx: 22, cy: 54, rx: 2, ry: 5.8, fill: LIGHT, opacity: 0.4, blur: 'soft' }],
    pulp:
      'M 20.5,54.5 C 18.8,60 18.8,70.5 21,76 C 24.5,79.5 38.5,79.5 41.8,76 C 44,70.5 44,60 42.2,54.5 C 36.8,57.6 25.8,57.6 20.5,54.5 Z',
    gum: 'M 8,47 Q 30,52.5 51.5,47',
    cervical: 'M 12,47 Q 30,50.8 48.5,47',
    relWidth: 1.15,
    apexCenter: { x: 30, y: 10 },
  },
  occlusal: {
    table:
      'M 14,63.5 C 20.5,61 43.5,61 49,63.5 C 50.9,70 50.6,77.5 48.7,82.8 C 43.5,88.5 19.5,88.5 14.6,82.8 C 12.8,77.5 12.5,70 14,63.5 Z',
    tableTopShade: { cx: 31.4, cy: 63, rx: 17, ry: 3.3, fill: SHADE_CUSP, opacity: 0.3, blur: 'wide' },
    shades: [
      cuspShade(31, 73.5, 7.5, 6.8, 0.34),
      cuspShade(20, 69, 4.8, 4.2, 0.2),
      cuspShade(41, 69, 4.8, 4.2, 0.2),
      cuspShade(20.2, 75, 3.2, 3.5, 0.13),
      cuspShade(41.2, 75, 3.2, 3.5, 0.13),
    ],
    lights: [
      cuspRidge(20, 70, 6.3, 4.4, -14, 0.95),
      cuspRidge(41, 70, 5.9, 4.2, 14, 0.92),
      cuspRidge(20.5, 80, 5.6, 3.8, -10, 0.89),
      cuspRidge(41.5, 80, 5.6, 3.8, 10, 0.89),
    ],
    grooves: [
      'M 30.8,63.5 C 30.6,70 30.6,77 30.8,83.5',
      'M 16.5,73 C 25,75.3 37.5,75.3 46.5,73',
    ],
  },
  roots: {
    trunks: [
      'M 15,48 C 13,38 14.5,22 24,11 C 26,8.6 30,8.6 32,10.8 C 42,21 46.5,36 44.5,48 C 36,51.8 23,51.8 15,48 Z',
    ],
    furcations: [],
    apexShadows: [apexShadow(31, 14, 3.5, 4)],
    grooves: [
      'M 29,16 C 28,28 28.5,38 29.5,45',
      'M 34.5,15 C 35.5,26 35.4,37 34.6,45',
    ],
    canals: [
      'M 27,12 C 26,26 26.5,40 28,54',
      'M 36,12 C 37,26 36.4,40 35,54',
    ],
    apices: [{ x: 30, y: 10 }],
    rootCount: 1,
    canalCount: 3,
  },
  fracture: 'M 15,49 L 25,64 L 21,76 L 36,92',
}

// ══════════════════════════════════════════════════════════════════════════════
// MANDIBULAR CLASS CONFIG (authored in the maxillary frame, then mirrored)
// ══════════════════════════════════════════════════════════════════════════════

/** Lower crown: reuse the maxillary crown base with a class width factor. */
function lowerCrown(upper: CrownBase, fx: number): CrownBase {
  return {
    outline: transformPathD(upper.outline, fx, 1),
    details: upper.details.map((d) => transformPathD(d, fx, 1)),
    shades: upper.shades.map((b) => transformBlob(b, fx, 1)),
    lights: upper.lights.map((b) => transformBlob(b, fx, 1)),
    pulp: transformPathD(upper.pulp, fx, 1),
    gum: upper.gum,
    cervical: upper.cervical,
    relWidth: Math.round(upper.relWidth * fx * 100) / 100,
    apexCenter: upper.apexCenter,
  }
}

/** 5-cusp occlusal table for the mandibular first molar (3 buccal + 2 lingual). */
const LO6_OCCLUSAL: OcclusalSet = {
  table:
    'M 12.5,63.5 C 19.5,60.5 43.5,60.5 50.5,63.5 C 52.8,70 52.5,78 50.8,84 C 45,90 19,90 13.2,84 C 11.4,78 11.2,70 12.5,63.5 Z',
  tableTopShade: { cx: 31.5, cy: 63, rx: 18.5, ry: 3.6, fill: SHADE_CUSP, opacity: 0.3, blur: 'wide' },
  shades: [
    cuspShade(31, 74.5, 10, 8, 0.36),
    cuspShade(18, 69, 5, 4.2, 0.2),
    cuspShade(44, 69, 5, 4.2, 0.2),
    cuspShade(24.5, 70.5, 4.4, 2.5, 0.14),
    cuspShade(37.5, 70.5, 4.4, 2.5, 0.14),
    cuspShade(31, 81.5, 4.4, 2.3, 0.12),
  ],
  lights: [
    cuspRidge(18, 70, 6.8, 4.6, -14, 0.95),
    cuspRidge(31, 68, 6.4, 4.5, 0, 0.95),
    cuspRidge(44, 70, 6.8, 4.6, 14, 0.95),
    cuspRidge(23, 81, 6.6, 4.3, -10, 0.95),
    cuspRidge(39, 81, 6.6, 4.3, 10, 0.95),
  ],
  grooves: [
    'M 31,63.5 C 30.8,70 30.8,77 31,84.5',
    'M 14.5,73.5 C 24,75.8 38,75.8 48.5,73.5',
    'M 19.5,66.5 C 24,70 28,72.5 30.3,74',
    'M 42.5,66.5 C 38,70 34,72.5 31.7,74',
  ],
}

/** Dominant single buccal cusp + transverse ridge ("snake-eyes") for lower PM1. */
const LO4_OCCLUSAL: OcclusalSet = {
  table:
    'M 19.5,64 C 25,61.2 38,61.2 43.5,64 C 45.5,70 45.3,78.5 43.6,84.5 C 39,89.3 25.5,89.3 21,84.5 C 19.2,78.5 19,70 19.5,64 Z',
  tableTopShade: { cx: 31.5, cy: 63.5, rx: 12.5, ry: 3.2, fill: SHADE_CUSP, opacity: 0.33, blur: 'wide' },
  shades: [
    cuspShade(31, 70, 8, 4.5, 0.2),
    cuspShade(26, 79, 6, 4, 0.16),
    cuspShade(38, 79, 6, 4, 0.16),
    cuspShade(32, 86, 2.8, 2.2, 0.13),
  ],
  lights: [
    cuspRidge(31, 84.5, 7.4, 4.8, 0, 0.95),
    cuspRidge(26, 86, 4.8, 3.4, -12, 0.85),
    cuspRidge(38, 86, 4.8, 3.4, 12, 0.85),
  ],
  grooves: [
    'M 22,65 C 21.5,71 21.7,78 23,84.5',
    'M 41,65 C 41.5,71 41.3,78 40,84.5',
  ],
  ridges: ['M 23,73 C 28.5,69.8 34.5,69.8 40,73'],
}

/** 3-cusp Y-groove pattern for the mandibular second premolar. */
const LO5_OCCLUSAL: OcclusalSet = {
  table:
    'M 19,64 C 24.8,61.2 38.8,61.2 44.5,64 C 46.5,70.5 46.2,79 44.3,85 C 38.8,90.3 24.8,90.3 20.4,85 C 18.5,79 18.2,70.5 19,64 Z',
  tableTopShade: { cx: 31.8, cy: 63.5, rx: 13, ry: 3.2, fill: SHADE_CUSP, opacity: 0.33, blur: 'wide' },
  shades: [cuspShade(31.5, 74, 6.5, 5.5, 0.28), cuspShade(32.3, 85, 3.4, 2.5, 0.13)],
  lights: [
    cuspRidge(25.5, 84.5, 6.3, 4.3, -10, 0.95),
    cuspRidge(39, 84.5, 6.1, 4.3, 10, 0.95),
    cuspLight(31.5, 73, 4.4, 0.88),
  ],
  grooves: [
    'M 31.5,64 C 31.3,67 31.3,69.5 31.5,72',
    'M 31.5,72 C 28.5,76 26.5,79 25.5,82',
    'M 31.5,72 C 34.5,76 36.5,79 37.5,82',
  ],
}

interface LowerClass {
  crownFx: number
  occlusal: OcclusalSet
  roots: RootSet
  fracture: string
}

const LO41: LowerClass = {
  crownFx: 0.78,
  occlusal: { shades: [], lights: [], grooves: [] },
  roots: {
    trunks: [
      'M 26,48 C 25,37 26.5,20 30,9.5 C 31,7.2 34,7.2 35,9.5 C 38,20 39,37 38,48 C 34.5,50.8 29.5,50.8 26,48 Z',
    ],
    furcations: [],
    apexShadows: [apexShadow(32.5, 12, 2.8, 3.4)],
    grooves: ['M 32,13 C 31.6,24 31.6,36 32,44'],
    canals: ['M 32.2,11 C 31.7,24 31.7,38 32,52'],
    apices: [{ x: 32.5, y: 8.5 }],
    rootCount: 1,
    canalCount: 1,
  },
  fracture: 'M 25,49 L 30,62 L 28,72 L 35,86',
}

const LO42: LowerClass = {
  crownFx: 0.85,
  occlusal: { shades: [], lights: [], grooves: [] },
  roots: {
    trunks: [
      'M 24.8,48 C 24,37.5 25.5,22 31,11 C 32,8.8 35,9.2 35.6,11.5 C 39,22 39.8,37 39,48 C 34.5,51 29.5,51 24.8,48 Z',
    ],
    furcations: [],
    apexShadows: [apexShadow(34.5, 13.5, 2.8, 3.6)],
    grooves: ['M 32.8,15 C 32.4,26 32.8,36 33,44'],
    canals: ['M 33.5,12 C 32,24 31.8,38 32,52'],
    apices: [{ x: 34.5, y: 9.5 }],
    rootCount: 1,
    canalCount: 1,
  },
  fracture: 'M 25,49 L 30,62 L 27.5,72 L 35,86',
}

const LO43: LowerClass = {
  crownFx: 0.92,
  occlusal: {
    // Single cusp: bright tip, flanking shoulders, central developmental groove
    table:
      'M 22.5,64.5 C 26.5,62 37.5,62 41.5,64.5 C 43.2,70.5 43,78.5 41.6,84.5 C 37.5,89.3 26.5,89.3 22.4,84.5 C 21,78.5 20.8,70.5 22.5,64.5 Z',
    tableTopShade: { cx: 32, cy: 64, rx: 10.5, ry: 3, fill: SHADE_CUSP, opacity: 0.3, blur: 'wide' },
    shades: [
      cuspShade(32, 79, 7.5, 6.5, 0.2),
      cuspShade(25, 72, 4, 5.5, 0.16),
      cuspShade(39, 72, 4, 5.5, 0.16),
    ],
    lights: [
      cuspLight(32, 85.5, 5.2, 0.95),
      cuspLight(26.5, 70, 4, 0.7),
      cuspLight(37.5, 70, 4, 0.7),
    ],
    grooves: [
      'M 32,73 C 31.8,77 31.8,80.5 32,84.5',
      'M 27,71 C 29,74 30.5,76.5 31.4,79',
      'M 37,71 C 35,74 33.5,76.5 32.6,79',
    ],
  },
  roots: {
    trunks: [
      'M 21.5,48 C 20.2,35 21.5,15 30,5.5 C 31.4,3.6 34.6,3.6 36,5.5 C 43.5,15 44,35 42.5,48 C 35.5,51.6 27.5,51.6 21.5,48 Z',
    ],
    furcations: [],
    apexShadows: [apexShadow(33.5, 9, 3.2, 4)],
    grooves: [
      'M 30,10 C 29.5,24 29.5,36 30.2,45',
      'M 34.5,10 C 35,24 35,36 34.3,45',
    ],
    canals: ['M 32.5,8 C 31.9,22 31.9,36 32.2,52'],
    apices: [{ x: 33, y: 5 }],
    rootCount: 1,
    canalCount: 1,
  },
  fracture: 'M 23,49 L 29.5,62 L 27,74 L 32.5,92',
}

const LO44: LowerClass = {
  crownFx: 0.98,
  occlusal: LO4_OCCLUSAL,
  roots: {
    trunks: [
      'M 22,48 C 20.5,36 22,16 30,7 C 31.4,4.8 34.6,4.8 36,7 C 43,16 43.5,36 42,48 C 35,51.8 27,51.8 22,48 Z',
    ],
    furcations: [],
    apexShadows: [apexShadow(33, 10, 3.2, 4)],
    grooves: ['M 31.5,12 C 31,24 31.2,36 32,45'],
    canals: ['M 33,9 C 32.2,24 32.2,38 32.5,52'],
    apices: [{ x: 33, y: 6 }],
    rootCount: 1,
    canalCount: 1,
  },
  fracture: 'M 22,49 L 29,63 L 26,75 L 35,91',
}

const LO45: LowerClass = {
  crownFx: 1.0,
  occlusal: LO5_OCCLUSAL,
  roots: {
    trunks: [
      'M 20.5,48 C 19,36 20.5,16 28.5,6.5 C 30,4.2 34.5,4.2 36,6.5 C 43,16 43.5,36 42,48 C 35,51.8 27,51.8 20.5,48 Z',
    ],
    furcations: [],
    apexShadows: [apexShadow(33, 10, 3.2, 4)],
    grooves: ['M 31.5,11 C 31,24 31.2,36 32,45'],
    canals: ['M 33,9 C 32.2,24 32.2,38 32.5,52'],
    apices: [{ x: 33, y: 6 }],
    rootCount: 1,
    canalCount: 1,
  },
  fracture: 'M 22,49 L 29,64 L 25.5,76 L 35.5,92',
}

const LO46: LowerClass = {
  crownFx: 1.0,
  occlusal: LO6_OCCLUSAL,
  roots: {
    trunks: [
      // Broad mesial root curving distally
      'M 10,48 C 8,38 8.5,20 14,9 C 15,6.5 18.5,6.6 19.5,9.2 C 24,20 25.5,36 26,48 C 21,50.8 14.5,50.8 10,48 Z',
      // Distal root, straighter
      'M 36,48 C 35.5,38 37,20 43,10 C 44.4,7.6 47.6,8.2 48.2,10.8 C 51.5,22 51.5,38 50,48 C 45,50.8 39,50.8 36,48 Z',
    ],
    furcations: [
      'M 25.5,48 C 26.3,38.5 27.7,30 30,23.5 C 32.6,30 33.9,38.5 34.5,48 C 32,50 28.2,50 25.5,48 Z',
    ],
    apexShadows: [
      apexShadow(17, 13, 3.2, 4),
      apexShadow(45, 14.5, 3.2, 4),
    ],
    grooves: [
      'M 16.5,14 C 16,26 17.5,38 19.5,46',
      'M 44.5,15 C 44.8,26 43.8,38 42.8,46',
    ],
    canals: [
      'M 17,12 C 18,26 21,40 24,54',
      'M 44,12 C 44,26 42,40 40,54',
    ],
    apices: [
      { x: 16.5, y: 8.5 },
      { x: 45.5, y: 10 },
    ],
    rootCount: 2,
    canalCount: 3,
  },
  fracture: 'M 13,49 L 24,65 L 20,77 L 36,93',
}

const LO47: LowerClass = {
  crownFx: 0.95,
  occlusal: {
    table:
      'M 13.5,63.5 C 20.3,60.8 42.7,60.8 48.5,63.5 C 50.5,70 50.2,77.5 48.4,83 C 43.5,89 19.7,89 14.8,83 C 12.9,77.5 12.6,70 13.5,63.5 Z',
    tableTopShade: { cx: 31, cy: 63, rx: 17.5, ry: 3.4, fill: SHADE_CUSP, opacity: 0.32, blur: 'wide' },
    shades: [
      cuspShade(31, 74, 8.5, 7.5, 0.36),
      cuspShade(20, 69, 4.8, 4.2, 0.2),
      cuspShade(41, 69, 4.8, 4.2, 0.2),
      cuspShade(20.5, 75, 3, 4, 0.13),
      cuspShade(41.5, 75, 3, 4, 0.13),
    ],
    lights: [
      cuspRidge(20, 70, 6.3, 4.4, -14, 0.95),
      cuspRidge(41, 70, 6.3, 4.4, 14, 0.92),
      cuspRidge(20, 80, 6.2, 4.2, -10, 0.95),
      cuspRidge(42, 80, 6.2, 4.2, 10, 0.95),
    ],
    grooves: [
      'M 30.8,63.5 C 30.6,70 30.6,77 30.8,84',
      'M 16.5,73 C 25,75.3 37,75.3 46,73',
    ],
  },
  roots: {
    trunks: [
      'M 13,48 C 11.5,38 12,20 17,10 C 18,7.6 21,7.8 21.8,10.3 C 24.5,20 25.5,36 26,48 C 22,50.5 16.5,50.5 13,48 Z',
      'M 38.5,48 C 38,38 39,20 43.5,11 C 44.6,8.6 47.5,9 48,11.4 C 50,22 49.8,38 48,48 C 44.5,50.5 41.5,50.5 38.5,48 Z',
    ],
    furcations: [
      'M 26.2,48 C 26.7,39.5 27.6,32.5 29.3,26.5 C 30.8,32.5 31.4,39.5 31.7,48 C 29.8,49.8 28,49.8 26.2,48 Z',
    ],
    apexShadows: [
      apexShadow(19.5, 13.5, 3, 3.8),
      apexShadow(46, 15, 3, 3.8),
    ],
    grooves: [
      'M 18.5,15 C 18.2,26 19,36 20,45',
      'M 44,16 C 44.2,26 43.5,36 42.8,45',
    ],
    canals: [
      'M 18.5,12 C 19,25 21,39 23.5,54',
      'M 43.5,13 C 43,25 41.5,39 39.5,54',
    ],
    apices: [
      { x: 19.5, y: 9 },
      { x: 46, y: 12 },
    ],
    rootCount: 2,
    canalCount: 3,
  },
  fracture: 'M 14,49 L 24,64 L 20,76 L 35,92',
}

const LO48: LowerClass = {
  crownFx: 0.92,
  occlusal: {
    table:
      'M 14.5,63.5 C 21,61.2 42.5,61.2 48,63.5 C 49.8,70 49.6,77.5 47.7,82.8 C 43,88.5 19.8,88.5 15.2,82.8 C 13.3,77.5 13.1,70 14.5,63.5 Z',
    tableTopShade: { cx: 31.3, cy: 63, rx: 17, ry: 3.3, fill: SHADE_CUSP, opacity: 0.3, blur: 'wide' },
    shades: [
      cuspShade(31.5, 74, 8, 7, 0.36),
      cuspShade(20.5, 69, 4.8, 4, 0.2),
      cuspShade(42, 69, 4.8, 4, 0.2),
      cuspShade(20.7, 75, 3, 4, 0.13),
      cuspShade(41.8, 75, 3, 4, 0.13),
    ],
    lights: [
      cuspRidge(20.5, 70, 6.1, 4.3, -14, 0.95),
      cuspRidge(42, 70, 5.9, 4.2, 14, 0.92),
      cuspRidge(21, 80, 6, 4.1, -10, 0.93),
      cuspRidge(42.5, 80, 6, 4.1, 10, 0.93),
    ],
    grooves: [
      'M 31.3,63.5 C 31.1,70 31.1,77 31.3,83.5',
      'M 17,73 C 25,75.3 38,75.3 46.5,73',
    ],
  },
  roots: {
    trunks: [
      'M 16,48 C 14.5,38 16.5,24 26,14 C 28,11.6 32,11.6 34,13.8 C 43,23 46,36 44,48 C 35.5,51.8 23.5,51.8 16,48 Z',
    ],
    furcations: [],
    apexShadows: [apexShadow(31, 17, 3.2, 3.8)],
    grooves: [
      'M 29.5,19 C 28.8,29 29.2,38 30,45',
      'M 34.5,19 C 35.2,29 35,38 34.4,45',
    ],
    canals: [
      'M 29,18 C 28.2,30 28.8,40 29.8,52',
      'M 34.5,18 C 35.2,30 34.8,40 34,52',
    ],
    apices: [{ x: 31, y: 13 }],
    rootCount: 1,
    canalCount: 2,
  },
  fracture: 'M 15,49 L 25,63 L 21.5,75 L 35.5,91',
}

// ─── ASSEMBLY ────────────────────────────────────────────────────────────────

function implantFor(bb: BBox, isUpper: boolean): { outline: string; threads: string[] } {
  const cx = r1((bb.x0 + bb.x1) / 2)
  const w = Math.min(11, Math.max(7.5, (bb.x1 - bb.x0) * 0.28))
  const top = isUpper ? 10 : 90
  const bot = isUpper ? 47 : 53
  const outline =
    `M ${r1(cx - w / 2)},${bot} L ${r1(cx + w / 2)},${bot} ` +
    `L ${r1(cx + w / 2 - 1.2)},${r1(top + 8)} C ${r1(cx + w / 2 - 1.2)},${top} ${r1(cx - w / 2 + 1.2)},${top} ${r1(cx - w / 2 + 1.2)},${r1(top + 8)} Z`
  const threads: string[] = []
  const start = isUpper ? top + 6 : bot - 6
  const dir = isUpper ? 1 : -1
  for (let i = 0; i < 5; i++) {
    const y = r1(start + dir * (i + 1) * 6.5)
    const t = i / 4
    const tw = r1((w - 1.5) * (1 - t * 0.35) / 2)
    threads.push(`M ${r1(cx - tw)},${y} L ${r1(cx + tw)},${y}`)
  }
  return { outline, threads }
}

function assemble(cls: ToothClass): Omit<ToothGeometryPaths, 'surfaces'> {
  const c = cls.crown
  const oc = cls.occlusal
  const rt = cls.roots
  return {
    rootOutline: rt.trunks.join(' '),
    rootDetails: rt.grooves,
    crownOutline: c.outline,
    crownDetails: c.details,
    pulpOutline: c.pulp,
    rootCanalPaths: rt.canals,
    implantOutline: '',
    implantThreads: [],
    crownCapOutline: '',
    apexCenter: c.apexCenter,
    apices: rt.apices,
    gumLinePath: c.gum,
    fractureCrackPath: cls.fracture,
    fissurePaths: oc.grooves,
    cuspHighlights: oc.ridges ?? [],
    rootSeparationPath: rt.furcations.join(' ') || undefined,
    cervicalLinePath: c.cervical,
    rootCount: rt.rootCount,
    canalCount: rt.canalCount,
    relativeWidth: c.relWidth,
    rootTrunks: rt.trunks,
    rootApexShadows: rt.apexShadows,
    rootGrooves: rt.grooves,
    furcationShadows: rt.furcations,
    crownShades: c.shades,
    occlusalShades: oc.shades,
    crownLights: [...c.lights, ...oc.lights],
    occlusalTablePath: oc.table,
    tableTopShade: oc.tableTopShade,
    occlusalGrooves: oc.grooves,
    occlusalRidges: oc.ridges,
  }
}

function finalize(g: Omit<ToothGeometryPaths, 'surfaces'>, isRightSide: boolean, isUpper: boolean): ToothGeometryPaths {
  const bb = pathBBox(g.crownOutline)
  const cx = (bb.x0 + bb.x1) / 2
  const cy = (bb.y0 + bb.y1) / 2
  const cap = transformPathD(g.crownOutline, 1.07, 1.07, cx, cy)
  const implant = implantFor(bb, isUpper)
  const fracture =
    `M ${r1(cx - 9)},${r1(bb.y0 + 2.5)} L ${r1(cx - 1)},${r1(cy)} L ${r1(cx - 5)},${r1(cy + (bb.y1 - cy) * 0.45)} L ${r1(cx + 6)},${r1(bb.y1 - 1.5)}`
  // Merged cervical base: extends the root trunks down behind the crown so the
  // trunk base edges never step out above the cervical line.
  let skirt: string | undefined
  if (g.rootTrunks.length > 0) {
    let x0 = Infinity
    let x1 = -Infinity
    for (const t of g.rootTrunks) {
      const b = pathBBox(t)
      x0 = Math.min(x0, b.x0)
      x1 = Math.max(x1, b.x1)
    }
    // Clamp to the crown's CERVICAL width (the band the skirt actually spans),
    // taken from the cervical line endpoints — the global bbox is wider on
    // narrowed crowns and let the skirt poke out beside the cervical.
    const cM = g.cervicalLinePath ? /M\s*(-?[\d.]+),\s*(-?[\d.]+)/.exec(g.cervicalLinePath) : null
    const cT = g.cervicalLinePath ? /(-?[\d.]+),\s*(-?[\d.]+)\s*$/.exec(g.cervicalLinePath) : null
    const cervX0 = cM ? +cM[1] : bb.x0 + 1.5
    const cervX1 = cT ? +cT[1] : bb.x1 - 1.5
    x0 = Math.max(x0, Math.min(cervX0, cervX1) + 1.0)
    x1 = Math.min(x1, Math.max(cervX0, cervX1) - 1.0)
    const topY = isUpper ? 49.2 : 44.8
    const botY = isUpper ? 55.5 : 51.5
    skirt = `M ${r1(x0)},${botY} L ${r1(x0)},${topY} Q ${r1((x0 + x1) / 2)},${r1(topY - 1.2)} ${r1(x1)},${topY} L ${r1(x1)},${botY} Z`
  }
  return {
    ...g,
    cervicalSkirt: skirt,
    surfaces: buildSurfaces(bb, isRightSide, isUpper),
    crownCapOutline: cap,
    implantOutline: implant.outline,
    implantThreads: implant.threads,
    fractureCrackPath: fracture,
  }
}

function flipGeometry(g: ToothGeometryPaths): ToothGeometryPaths {
  return {
    ...g,
    rootOutline: g.rootTrunks.map(flipX).join(' '),
    crownOutline: flipX(g.crownOutline),
    crownDetails: g.crownDetails?.map(flipX),
    pulpOutline: flipX(g.pulpOutline),
    rootCanalPaths: g.rootCanalPaths.map(flipX),
    implantOutline: flipX(g.implantOutline),
    implantThreads: g.implantThreads.map(flipX),
    crownCapOutline: flipX(g.crownCapOutline),
    apexCenter: { x: r1(64 - g.apexCenter.x), y: g.apexCenter.y },
    apices: g.apices?.map((p) => ({ x: r1(64 - p.x), y: p.y })),
    gumLinePath: flipX(g.gumLinePath),
    fractureCrackPath: flipX(g.fractureCrackPath),
    fissurePaths: g.fissurePaths?.map(flipX),
    cuspHighlights: g.cuspHighlights?.map(flipX),
    rootSeparationPath: g.rootSeparationPath ? flipX(g.rootSeparationPath) : undefined,
    cervicalSkirt: g.cervicalSkirt ? flipX(g.cervicalSkirt) : undefined,
    cervicalLinePath: g.cervicalLinePath ? flipX(g.cervicalLinePath) : undefined,
    rootTrunks: g.rootTrunks.map(flipX),
    rootApexShadows: g.rootApexShadows.map(flipXBlob),
    rootGrooves: g.rootGrooves.map(flipX),
    furcationShadows: g.furcationShadows.map(flipX),
    crownShades: g.crownShades.map(flipXBlob),
    occlusalShades: g.occlusalShades.map(flipXBlob),
    crownLights: g.crownLights.map(flipXBlob),
    occlusalTablePath: g.occlusalTablePath ? flipX(g.occlusalTablePath) : undefined,
    tableTopShade: g.tableTopShade ? flipXBlob(g.tableTopShade) : undefined,
    occlusalGrooves: g.occlusalGrooves.map(flipX),
    occlusalRidges: g.occlusalRidges?.map(flipX),
    // Mesial/distal swap under horizontal mirror
    surfaces: {
      mesial: g.surfaces.distal,
      distal: g.surfaces.mesial,
      occlusal: g.surfaces.occlusal,
      buccal: g.surfaces.buccal,
      lingual: g.surfaces.lingual,
    },
  }
}

// ─── PROPORTIONAL REFINEMENT PASS ────────────────────────────────────────────
// Widen crowns toward real mesiodistal proportions and trim roots (thinner,
// shorter, tighter taper) without re-authoring the hand-tuned curves.

function scaleClass(cls: ToothClass, crownFx: number, rootFx: number, rootFy: number): ToothClass {
  const bb = pathBBox(cls.crown.outline)
  const cx = (bb.x0 + bb.x1) / 2
  const sc = (d: string, fx: number, fy: number, oy = 48) => transformPathD(d, fx, fy, cx, oy)
  const sb = (b: VolBlob, fx: number, fy: number, oy = 48) => transformBlob(b, fx, fy, cx, oy)
  return {
    ...cls,
    crown: {
      ...cls.crown,
      outline: sc(cls.crown.outline, crownFx, 1),
      details: cls.crown.details.map((d) => sc(d, crownFx, 1)),
      shades: cls.crown.shades.map((b) => sb(b, crownFx, 1)),
      lights: cls.crown.lights.map((b) => sb(b, crownFx, 1)),
      pulp: sc(cls.crown.pulp, crownFx, 1),
      gum: sc(cls.crown.gum, crownFx, 1),
      cervical: sc(cls.crown.cervical, crownFx, 1),
    },
    occlusal: {
      ...cls.occlusal,
      table: cls.occlusal.table ? sc(cls.occlusal.table, crownFx, 1) : undefined,
      tableTopShade: cls.occlusal.tableTopShade ? sb(cls.occlusal.tableTopShade, crownFx, 1) : undefined,
      shades: cls.occlusal.shades.map((b) => sb(b, crownFx, 1)),
      lights: cls.occlusal.lights.map((b) => sb(b, crownFx, 1)),
      grooves: cls.occlusal.grooves.map((d) => sc(d, crownFx, 1)),
      ridges: cls.occlusal.ridges?.map((d) => sc(d, crownFx, 1)),
    },
    roots: {
      ...cls.roots,
      trunks: cls.roots.trunks.map((d) => sc(d, rootFx, rootFy)),
      furcations: cls.roots.furcations.map((d) => sc(d, rootFx, rootFy)),
      apexShadows: cls.roots.apexShadows.map((b) => sb(b, rootFx, rootFy)),
      grooves: cls.roots.grooves.map((d) => sc(d, rootFx, rootFy)),
      canals: cls.roots.canals.map((d) => sc(d, rootFx, rootFy)),
      apices: cls.roots.apices.map((p) => ({ x: r1(cx + (p.x - cx) * rootFx), y: r1(48 + (p.y - 48) * rootFy) })),
    },
  }
}

// ─── MASTER TABLE ────────────────────────────────────────────────────────────

const UPPER_CLASSES: Record<number, ToothClass> = {
  1: scaleClass(UP11, 1.22, 0.88, 0.95),
  2: scaleClass(UP12, 1.18, 0.86, 0.95),
  3: scaleClass(UP13, 1.12, 0.94, 0.97),
  4: scaleClass(UP14, 1.1, 0.95, 0.96),
  5: scaleClass(UP15, 1.1, 0.95, 0.96),
  6: scaleClass(UP16, 1.0, 0.97, 0.97),
  7: scaleClass(UP17, 1.0, 0.97, 0.97),
  8: scaleClass(UP18, 1.0, 0.98, 0.97),
}

const LOWER_CLASSES: Record<number, LowerClass> = {
  1: LO41,
  2: LO42,
  3: LO43,
  4: LO44,
  5: LO45,
  6: LO46,
  7: LO47,
  8: LO48,
}

function assembleUpper(digit: number): ToothGeometryPaths {
  return finalize(assemble(UPPER_CLASSES[digit]), true, true)
}

/** Mirror an upper-frame geometry into the mandibular frame (crowns up, roots down). */
function mirrorToMandibularFrame(g: Omit<ToothGeometryPaths, 'surfaces'>): Omit<ToothGeometryPaths, 'surfaces'> {
  return {
    ...g,
    rootOutline: g.rootTrunks.map(mirrorY).join(' '),
    crownOutline: mirrorY(g.crownOutline),
    crownDetails: g.crownDetails?.map(mirrorY),
    pulpOutline: mirrorY(g.pulpOutline),
    rootCanalPaths: g.rootCanalPaths.map(mirrorY),
    apexCenter: { x: g.apexCenter.x, y: r1(100 - g.apexCenter.y) },
    apices: g.apices?.map((p) => ({ x: p.x, y: r1(100 - p.y) })),
    gumLinePath: mirrorY(g.gumLinePath),
    fissurePaths: g.fissurePaths?.map(mirrorY),
    cuspHighlights: g.cuspHighlights?.map(mirrorY),
    rootSeparationPath: g.rootSeparationPath ? mirrorY(g.rootSeparationPath) : undefined,
    cervicalSkirt: g.cervicalSkirt ? mirrorY(g.cervicalSkirt) : undefined,
    cervicalLinePath: g.cervicalLinePath ? mirrorY(g.cervicalLinePath) : undefined,
    rootTrunks: g.rootTrunks.map(mirrorY),
    rootApexShadows: g.rootApexShadows.map(mirrorYBlob),
    rootGrooves: g.rootGrooves.map(mirrorY),
    furcationShadows: g.furcationShadows.map(mirrorY),
    crownShades: g.crownShades.map(mirrorYBlob),
    occlusalShades: g.occlusalShades.map(mirrorYBlob),
    crownLights: g.crownLights.map(mirrorYBlob),
    occlusalTablePath: g.occlusalTablePath ? mirrorY(g.occlusalTablePath) : undefined,
    tableTopShade: g.tableTopShade ? mirrorYBlob(g.tableTopShade) : undefined,
    occlusalGrooves: g.occlusalGrooves.map(mirrorY),
    occlusalRidges: g.occlusalRidges?.map(mirrorY),
  }
}

function assembleLower(digit: number): ToothGeometryPaths {
  const lo = LOWER_CLASSES[digit]
  const up = UPPER_CLASSES[digit]
  const cls: ToothClass = {
    crown: lowerCrown(up.crown, lo.crownFx),
    occlusal: lo.occlusal,
    roots: lo.roots,
    fracture: lo.fracture,
  }
  const upperFrame = assemble(cls)
  // Mirror into the mandibular frame, then finalize procedural parts
  // (surfaces, implant, crown cap, fracture) from the final frame.
  return finalize(mirrorToMandibularFrame(upperFrame), true, false)
}

const GEOMETRY_CACHE = new Map<number, ToothGeometryPaths>()

function getGeometryCached(num: number): ToothGeometryPaths {
  const hit = GEOMETRY_CACHE.get(num)
  if (hit) return hit
  const digit = num % 10
  const quadrant = Math.floor(num / 10)
  let geom: ToothGeometryPaths
  if (quadrant === 1) geom = assembleUpper(digit)
  else if (quadrant === 2) geom = flipGeometry(assembleUpper(digit))
  else if (quadrant === 4) geom = assembleLower(digit)
  else geom = flipGeometry(assembleLower(digit))
  GEOMETRY_CACHE.set(num, geom)
  return geom
}

// ─── PUBLIC API ──────────────────────────────────────────────────────────────

export function getToothSpecificType(toothNumber: number): ToothSpecificType {
  const d = toothNumber % 10
  const upper = Math.floor(toothNumber / 10) <= 2
  const names: Record<number, [ToothSpecificType, ToothSpecificType]> = {
    1: ['maxillary_central_incisor', 'mandibular_central_incisor'],
    2: ['maxillary_lateral_incisor', 'mandibular_lateral_incisor'],
    3: ['maxillary_canine', 'mandibular_canine'],
    4: ['maxillary_first_premolar', 'mandibular_first_premolar'],
    5: ['maxillary_second_premolar', 'mandibular_second_premolar'],
    6: ['maxillary_first_molar', 'mandibular_first_molar'],
    7: ['maxillary_second_molar', 'mandibular_second_molar'],
    8: ['maxillary_third_molar', 'mandibular_third_molar'],
  }
  const pair = names[d] ?? names[1]
  return upper ? pair[0] : pair[1]
}

/**
 * Returns exact vector geometry by tooth number, or falls back to group/position/side.
 */
export function getToothGeometry(
  group: ToothAnatomyGroup,
  position: ToothPosition,
  side: ToothSide,
  toothNumber?: number
): ToothGeometryPaths {
  if (toothNumber) {
    return getToothGeometryByNumber(toothNumber)
  }

  const isUpper = position === 'upper'
  const isRight = side === 'right'
  const digit = group === 'molar' ? 6 : group === 'premolar' ? 4 : group === 'canine' ? 3 : 1
  const num = (isUpper ? (isRight ? 1 : 2) : isRight ? 4 : 3) * 10 + digit
  return getToothGeometryByNumber(num)
}

/**
 * Precision anatomical geometry for every individual tooth (11 to 48).
 */
export function getToothGeometryByNumber(toothNumber: number): ToothGeometryPaths {
  return getGeometryCached(toothNumber)
}
