"""
Liodon engine service tests (Phase 19A).

Covers the gate-relevant engine behaviour:
  - model existence / checksum gate (mismatched artifact is refused, even
    with ALLOW_STANDIN, unless the file self-declares as the stand-in)
  - CPUExecutionProvider only
  - model loading (stand-in graph, generated by the lab's own tooling)
  - real ONNX inference (synthetic stand-in — plumbing evidence, NOT the
    Liodon model; real best.onnx runs are validated on the deployment
    machine against the registry SHA-256)
  - output schema (condition / confidence / bounding box / provenance)
  - /health + /infer endpoints
"""

from __future__ import annotations

import base64
import hashlib
import math

import pytest

from fastapi.testclient import TestClient

from app import model as model_mod

KNOWN_CLASSES = ("caries", "periapical_lesion", "impacted_tooth")


# ---------------------------------------------------------------------------
# Model loading / checksum gate
# ---------------------------------------------------------------------------


def test_checksum_gate_rejects_missing_file(tmp_path):
    with pytest.raises(model_mod.ModelRejectedError):
        model_mod.load_model(tmp_path / "best.onnx")


def test_checksum_gate_rejects_non_onnx_extension(tmp_path):
    fake = tmp_path / "best.pt"
    fake.write_bytes(b"weights")
    with pytest.raises(model_mod.ModelRejectedError):
        model_mod.load_model(fake)


def test_checksum_gate_rejects_mismatched_best_onnx(tmp_path):
    fake = tmp_path / "best.onnx"
    fake.write_bytes(b"definitely-not-the-validated-artifact")
    with pytest.raises(model_mod.ModelRejectedError):
        model_mod.load_model(fake)


def test_checksum_gate_still_rejects_with_allow_standin_but_no_declaration(tmp_path):
    # ALLOW_STANDIN must never become a hole for a tampered real model.
    fake = tmp_path / "best.onnx"
    fake.write_bytes(b"tampered-real-weights")
    with pytest.raises(model_mod.ModelRejectedError):
        model_mod.load_model(fake, allow_standin=True)


def test_standin_loads_flagged_and_cpu_only(standin_path):
    m = model_mod.load_model(standin_path, allow_standin=True)
    assert m.is_standin is True
    assert m.sha256 != m.sha256_expected  # not the real artifact
    assert m.input_name == "images"
    assert m.output_name == "output0"
    assert m.input_shape == [1, 3, 640, 640]
    assert m.output_shape == [1, 7, 8400]
    assert m.class_names.get(0) == "caries"
    assert m.session.get_providers() == ["CPUExecutionProvider"]


# ---------------------------------------------------------------------------
# Inference (validated pipeline, stand-in weights)
# ---------------------------------------------------------------------------


def test_inference_output_schema(standin_path, synthetic_image_bytes):
    m = model_mod.load_model(standin_path, allow_standin=True)
    res = model_mod.run_inference(m, synthetic_image_bytes)

    assert res["is_standin_not_liodon"] is True
    # Stand-in doc: 3 detections after conf filter + per-class NMS.
    assert res["detection_count"] == 3
    assert res["image"]["sha256"] == hashlib.sha256(synthetic_image_bytes).hexdigest()
    assert res["raw_model_output"]["shape"] == [1, 7, 8400]
    assert res["raw_model_output"]["num_channels"] == 7
    assert res["raw_model_output"]["num_classes"] == 3

    for d in res["detections"]:
        assert d["condition"] in KNOWN_CLASSES
        assert d["class_name"] == d["condition"]
        assert d["tooth_number"] is None  # the model has no tooth numbering
        assert 0.0 <= d["confidence"] <= 1.0
        b = d["bbox"]
        assert b["units"] == "pixels"
        assert b["coordinate_space"] == "original_image"
        for key in ("x1", "y1", "x2", "y2", "x", "y", "width", "height"):
            assert math.isfinite(b[key]), key
        # Original image is 2400x1200: boxes must be in that space.
        assert 0 <= b["x1"] < b["x2"] <= 2400
        assert 0 <= b["y1"] < b["y2"] <= 1200
        assert b["width"] == b["x2"] - b["x1"]
        assert b["height"] == b["y2"] - b["y1"]

    assert "total_ms" in res["timings_ms"]
    assert res["annotated_png_hex"]  # separate annotated output produced
    assert res["parameters"]["conf"] == 0.45
    assert res["parameters"]["iou"] == 0.35


def test_inference_zero_findings_is_valid(standin_path):
    # conf=1.0 filters everything out -> a completed analysis with 0 findings.
    from PIL import Image

    import io

    m = model_mod.load_model(standin_path, allow_standin=True)
    img = Image.new("RGB", (640, 320), (30, 30, 30))
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    res = model_mod.run_inference(m, buf.getvalue(), conf=1.0)
    assert res["detection_count"] == 0
    assert res["detections"] == []


# ---------------------------------------------------------------------------
# HTTP surface
# ---------------------------------------------------------------------------


def test_health_endpoint_reports_loaded_model(synthetic_image_bytes):
    from app.main import app

    client = TestClient(app)
    h = client.get("/health").json()
    assert h["status"] == "ok"
    assert h["model_loaded"] is True
    assert h["model_name"] == "liodon"
    assert h["model_version"] == "1.0.0"
    assert h["model_license"] == "CC-BY-NC-4.0"
    assert h["model_source"].startswith("https://huggingface.co/liodon-ai/dental-panoramic-detector")
    assert h["device"] == "cpu"
    assert h["runtime"]["execution_provider"] == "CPUExecutionProvider"
    assert h["is_standin_not_liodon"] is True
    assert h["model_checksum_verified"] is True
    assert h["tensor_input"]["shape"] == [1, 3, 640, 640]
    assert h["tensor_output"]["shape"] == [1, 7, 8400]


def test_infer_endpoint_returns_structured_findings(synthetic_image_bytes):
    from app.main import app

    client = TestClient(app)
    r = client.post(
        "/infer",
        json={"image": base64.b64encode(synthetic_image_bytes).decode()},
    )
    assert r.status_code == 200
    body = r.json()
    assert body["detection_count"] == 3
    assert body["is_standin_not_liodon"] is True
    assert body["device"] == "cpu"
    assert body["model"]["model_sha256"]
    assert body["model"]["model_version"] == "1.0.0"
    assert body["annotated_png_hex"]
    for d in body["detections"]:
        assert d["condition"] in KNOWN_CLASSES
        assert 0.0 <= d["confidence"] <= 1.0


def test_infer_endpoint_rejects_invalid_base64():
    from app.main import app

    client = TestClient(app)
    r = client.post("/infer", json={"image": "!!not-base64!!"})
    assert r.status_code == 400
